spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.31.90:3306/xcm-admin?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 180
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: false
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    check-template-location: true
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    content-type: text/html
    enabled: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      tag_syntax: auto_detect
      number_format: 0.######
  redis:
    host: 192.168.31.90
    password:
    port: 6379
    database: 0
    timeout: 3s
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 10
        max-wait: 3s